# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 347c3b174271296569ce14aac1e4993c2d18ed1776b13ec89efd8d3fa9db53d80b971c4fc2bb1d2f20059b89a484b6c86251ca9ec3d2047d2928f3d2a3c902af

test:
  secret_key_base: 6befc7e7b091e9ce456b2f91dba1719f5075761eecb0937e441665802323e4d9e27cd2b221ed48b3056b85735d447bf5ec1aec391629e30ff5cfba88ba245e4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
